sudo: false

language:
    - php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
  - PHPCS_BRANCH=master
  - PHPCS_BRANCH=2.2.0

matrix:
  include:
    # Run against PHPCS 3.0. I just picked to run it against 5.6.
    - php: 5.6
      env: PHPCS_BRANCH=3.0
    # Run against HHVM and PHP nightly.
    - php: hhvm
      env: PHPCS_BRANCH=master
    - php: nightly
      env: PHPCS_BRANCH=master
  allow_failures:
    # Allow failures for unstable builds.
    - php: nightly
    - php: hhvm
    - env: PHPCS_BRANCH=3.0

before_script:
    - export PHPCS_DIR=/tmp/phpcs
    - mkdir -p $PHPCS_DIR && git clone --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git -b $PHPCS_BRANCH $PHPCS_DIR
    - $PHPCS_DIR/scripts/phpcs --config-set installed_paths $(pwd)

script:
    - find . \( -name '*.php' \) -exec php -lf {} \;
    - phpunit --filter WordPress /tmp/phpcs/tests/AllTests.php
