language:
    - php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - git clone --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git /tmp/phpcs
    - project_dir=$(pwd) && cd /tmp/phpcs/CodeSniffer/Standards && mv $project_dir ./WordPress && cd WordPress

script:
    - find . \( -name '*.php' \) -exec php -lf {} \;
    - phpunit --filter WordPress /tmp/phpcs/tests/AllTests.php
