language:
    - php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - export PHPCS_GITHUB_SRC=squizlabs/PHP_CodeSniffer
    - export PHPCS_DIR=/tmp/phpcs
    - export PHPCS_GIT_TREE=master
    - mkdir -p $PHPCS_DIR && curl -L https://github.com/$PHPCS_GITHUB_SRC/archive/$PHPCS_GIT_TREE.tar.gz | tar xvz --strip-components=1 -C $PHPCS_DIR
    - $PHPCS_DIR/scripts/phpcs --config-set installed_paths $(pwd)

script:
    - find . \( -name '*.php' \) -exec php -lf {} \;
    - phpunit --filter WordPress /tmp/phpcs/tests/AllTests.php
